import {
  Settings,
  GitCommit,
  Bell,
  Send,
  Shield,
  Sparkles,
  Monitor,
  Terminal,
  Twitter,
  Cloud,
} from 'lucide-react';
import { SlackIcon } from './SlackIcon';
import { JiraIcon } from './JiraIcon';
import { TasmaniaIcon } from './TasmaniaIcon';
import { ObsidianIcon } from './ObsidianIcon';
import type { SettingsSection } from './types';

export const SECTIONS: { id: SettingsSection; label: string; icon: React.ComponentType<{ className?: string }> }[] = [
  { id: 'general', label: 'General', icon: Settings },
  { id: 'terminal', label: 'Terminal', icon: Terminal },
  { id: 'obsidian', label: 'Obsidian', icon: ObsidianIcon },
  { id: 'git', label: 'Git', icon: GitCommit },
  { id: 'notifications', label: 'Notifications', icon: Bell },
  { id: 'telegram', label: 'Telegram', icon: Send },
  { id: 'slack', label: 'Slack', icon: SlackIcon },
  { id: 'jira', label: 'JIRA', icon: JiraIcon },
  { id: 'socialdata', label: 'X (Twitter)', icon: Twitter },
  { id: 'tasmania', label: 'Tasmania', icon: TasmaniaIcon },
  { id: 'google-workspace', label: 'Google Workspace', icon: Cloud },
  { id: 'permissions', label: 'Permissions', icon: Shield },
  { id: 'skills', label: 'Skills & Plugins', icon: Sparkles },
  { id: 'cli', label: 'CLI Paths', icon: Terminal },
  { id: 'system', label: 'System', icon: Monitor },
];

export const DEFAULT_APP_SETTINGS = {
  notificationsEnabled: true,
  notifyOnWaiting: true,
  notifyOnComplete: true,
  notifyOnError: true,
  telegramEnabled: false,
  telegramBotToken: '',
  telegramChatId: '',
  telegramAuthToken: '',
  telegramAuthorizedChatIds: [] as string[],
  telegramRequireMention: false,
  slackEnabled: false,
  slackBotToken: '',
  slackAppToken: '',
  slackSigningSecret: '',
  slackChannelId: '',
  jiraEnabled: false,
  jiraDomain: '',
  jiraEmail: '',
  jiraApiToken: '',
  socialDataEnabled: false,
  socialDataApiKey: '',
  xPostingEnabled: false,
  xApiKey: '',
  xApiSecret: '',
  xAccessToken: '',
  xAccessTokenSecret: '',
  tasmaniaEnabled: false,
  tasmaniaServerPath: '',
  gwsEnabled: false,
  gwsSkillsInstalled: false,
  verboseModeEnabled: false,
  autoCheckUpdates: true,
  defaultProvider: 'claude',
  obsidianVaultPaths: [] as string[],
  terminalFontSize: 11,
  terminalTheme: 'dark' as const,
  cliPaths: {
    claude: '',
    codex: '',
    gemini: '',
    gws: '',
    gcloud: '',
    gh: '',
    node: '',
    additionalPaths: [],
  },
};
